import React, { Component } from 'react';
import './SectionFour.css'
import Logo1 from '../../../images/logo01.png'
export default class About extends Component {
render()
{
return(
<div className="pl-3 pr-3">
<div className="container-fluid" style={{backgroundColor:"#f3f3f3"}}>
<div className="container afterimage" data-aos="fade-right">
<h1 className="modifiedtext" >THE TALENT BEHIND THE REPUTATION</h1>
<h2 style={{fontFamily:"lora",fontStyle:"italic",color:"rgb(146, 146, 146)",paddingBottom:"20px",paddingTop:"20px"}}>Design your interior to be timeless, sustainable, efficient and beautiful.</h2>
<p className="fourthsectionpara"><strong>Home & Decor</strong> is a full service, Ambarawa City interior design firm specializing in classic design with a global influence. Whether designing residential or commercial spaces, H&D has built a reputation on achieving highly individual results for a discerning, international clientele.</p>
<p className="fourthsectionpara">H&D crafts visual stories that become signature surroundings.  Guided by clients’ aspirations, as well as their diverse experiences, the firm designs singular interiors, which allow clients to fully express who they are, and what holds meaning to them.</p>
<p className="fourthsectionpara">The history and location of the project, coupled with H&D’s broad base of experience, and its firm belief that successful design must be generated by the individual characteristics of each project, lets H&D create extraordinary interiors. A portfolio of completed work includes historic restorations, contemporary renovations and new construction projects.</p>
<p className="fourthsectionpara">Supported by an underlying thread of sustainable quality, Home & Decor ensures that the clients’ greatest investment is also their greatest source of comfort, pride and self-expression.</p>
<h1 className="modifiedtext" style={{fontSize:"35px",paddingTop:"30px"}}>SOME OF OUR WORK HAS BEEN AWARDED OR FEATURED</h1>
<div className="row pt-5 pb-5">
<div className="col-md-3 col-sm-12 alignment pt-1">
<img src={Logo1}/>
</div>
<div className="col-md-3 col-sm-12 alignment pt-1">
<img src={Logo1}/>
</div>
<div className="col-md-3 col-sm-12 alignment pt-1">
<img src={Logo1}/>
</div>
<div className="col-md-3 col-sm-12 alignment pt-1">
<img src={Logo1}/>
</div>
</div>
</div>
</div>
</div>
)
}
}